### ISSUE TITLE
fix: reduce installer size

### ISSUE THREAD

**Issue by andrewbenington** [andrewbenington/OpenHome#31]
**Description**
The current application includes images for each Pokémon and each generation, which results in a large installer and application size. By default the application should only include Pokémon Home images, with the option to download other sprites separately

Fix requested by @RodrigoTR04

**Comment by evanwporter** [comment]
We can cut the size by 200 mb just by adding a conditional to download LGPE sprites.

**Comment by andrewbenington** [comment]
Wait for real? 🤦‍♂️

I personally love the different sprites per save type, but right now its not worth the space it takes up. I'm going to see how much space compressing them could save, and if that's not enough I'll make them an optional download and default to the Home sprites for every save type

**Comment by andrewbenington** [comment]
that’s part of it, but i have shiny version of all the generations’ sprites. the real reason is because the LGPE sprites are SUPER high resolution, which i didn’t realize until recently. regardless it will be fixed when i make them separately downloadable

**Comment by evanwporter** [comment]
Another possible way to reduce the installer size is to use [tauri](https://tauri.app/) instead of electron. This may reduce the installer size by 2-300 MB. This is not a simple fix of course, but its also not as difficult as it may seem at first. Basically one would need to convert all of the listeners in `src/main/` to Rust code as well as define a data structure to pass the file data from type script to rust and vice versa using serde. Basically the basic commands like `removeRecentSaveFromFile` and `writeRecentSaves` (I just Copied+Pasted to random functions from `saves.ts`) basically everything that forms the backend would need to be moved to rust, but all of the types and stuff could be retained as typescript. May be more work than its worth. But also with tauris we get IOS support so thats fun...

**Comment by andrewbenington** [comment]
I have never heard of tauri, but I'm interested. I've wanted to do something with Rust for a while, and there's really not much backend code to begin with. Have you used tauri before?

**Comment by andrewbenington** [comment]
If Tauri is like React Native, then there should be a way to build an app for the App Store using Xcode tools.

I've been messing around with Tauri, and I think it will work. I'll have a branch up soon.

**Comment by evanwporter** [comment]
@andrewbenington  I also began messing with Tauri, but I haven't gotten too far. I made this menu and that's it:

```
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use tauri::{menu::*, Builder};

fn main() {
    Builder::default()
        .setup(|app| {
            let handle = app.handle();
            let menu = Menu::new(handle)?;

            let new_item = MenuItem::with_id(handle, "new", "New", true, None::<&str>)?;
            let open_item = MenuItem::with_id(handle, "open", "Open", true, None::<&str>)?;
            let save_item = MenuItem::with_id(handle, "save", "Save", true, None::<&str>)?;
            let exit_item = MenuItem::with_id(handle, "exit", "Exit", true, None::<&str>)?;

            let file_submenu = SubmenuBuilder::new(handle, "File")
                .item(&new_item)
                .item(&open_item)
                .item(&save_item)
                .separator()
                .item(&exit_item)
                .build()?;

            menu.append(&file_submenu)?;

            let _ = app.set_menu(menu);

            Ok(())
        })
        .on_menu_event(|_, event| {
            println!("Triggered menu event ID: {}", event.id.as_ref());
            match event.id.as_ref() {
                // File menu actions
                "new" => println!("New file action triggered!"),
                "open" => println!("Open file action triggered!"),
                "save" => println!("Save file action triggered!"),
                "exit" => std::process::exit(0),

                // Edit menu actions
                "undo" => println!("Undo action triggered!"),
                "redo" => println!("Redo action triggered!"),
                "cut" => println!("Cut action triggered!"),
                "copy" => println!("Copy action triggered!"),
                "paste" => println!("Paste action triggered!"),

                // View menu actions
                "zoom_in" => println!("Zoom In action triggered!"),
                "zoom_out" => println!("Zoom Out action triggered!"),
                "show_toolbar" => println!("Toggle toolbar action triggered!"),

                // Help menu actions
                "about" => println!("About dialog action triggered!"),
                "check_updates" => println!("Check for updates action triggered!"),

                _ => println!("Nothing triggered!"),
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running Tauri application");
}
```

**Comment by andrewbenington** [comment]
awesome, I've recreated most of the backend so we've been working on different parts.

**Comment by evanwporter** [comment]
> awesome, I've recreated most of the backend so we've been working on different parts.

@andrewbenington This is the only frontend portion that needs to be in rust. Everything else can be left in Javascript. I stopped after this point because I didn't want to dive into how the backend worked since that would require a better understanding.

**Comment by andrewbenington** [comment]
Anything that interfaces with the operating system, like reading and writing files, needs to go through rust. i'm trying to make the rust backend API as flexible as possible so most of the specific logic can be done with JavaScript.

I'm making use of the `fp-ts` library to convert between the `Result` type in Rust and the Either type in `fp-ts` TypeScript, which is a pretty seamless logical transition between the two

**Comment by evanwporter** [comment]
> Anything that interfaces with the operating system, like reading and writing files, needs to go through rust.

Hmm. I meant that the menu is the only frontend/user-facing part that needs to be done in rust. Also while its probably good to read/write the files in rust, Tauri has a JS module that allows access to the file system.

https://v1.tauri.app/v1/api/js/fs

**Comment by andrewbenington** [comment]
Regardless we would have to rewrite the `main` electron backend code to a Tauri equivalent, and while the performance increase probably won't matter, I just really like Rust. I'll have the branch ready in the next few days

**Comment by evanwporter** [comment]
>I just really like Rust.

Rust is actually insane. For a long time I had dismissed it as an inferior C++. But man was I wrong. The syntax feels more intuitive, the QoL features more apparent, Cargo is incredible, and most of all it doesn't feel like I'm trying to reinvent the wheel every time I type out a line of code.
