### ISSUE TITLE
feat: option to override system theme

### ISSUE THREAD

**Issue by Astranautica** [andrewbenington/OpenHome#61]
I may be just blind but I was curious on how to get a lighter theme for the awesome program!
![image_2024-11-26_192631361](https://github.com/user-attachments/assets/66be24ea-4e0e-4a0e-8f64-e6e71bab3946)

**Comment by andrewbenington** [comment]
Right now it follows whatever your operating system's default is. Being able to manually set the mode is a good feature to have though, I'll work on that soon. Thanks for creating an issue!

**Comment by Astranautica** [comment]
Awesome, I low key forgot windows even had a light mode its been so long lol.

A manual setting would be amazing, also I would like to add that it seems the box-data .txt doesn't reflect changes made to box names, and when force reload/ restart manually it defaults back to "Box 1".

Your work is awesome and helping me relive my childhood without restrictions on the consoles or fees!

**Comment by andrewbenington** [comment]
That makes me so happy! I'm glad you like it, and I'm going to keep working on adding missing features.

Renaming boxes is something that I just never got around to, but I'm sure that would be useful to most users. If you create and issue for that I will add it to the next release.
