### ISSUE TITLE
Renaming Boxes, Moving mons between boxes

### ISSUE THREAD

**Issue by Astranautica** [andrewbenington/OpenHome#62]
The ability to name boxes, with potential to gave different wallpapers like the games!

Moving mons between boxes when dragging them on the interface can cause the boxes to go from 1- box 36 in a second or less.

Thank you for hearing my feedback I cant praise this and you enough! Happy holidays as well.

**Comment by andrewbenington** [comment]
Moving between boxes should be fixed now, my next goal is to work on naming boxes
