### ISSUE TITLE
.pk9 does not work

### ISSUE THREAD

**Issue by Pat4tis** [andrewbenington/OpenHome#66]
i tried to transfer my Pokémon: violet save but .pk9 does not seem to open i tried .bin also does not work hope it get fixed to excited to try this project

**Comment by andrewbenington** [comment]
> i tried to transfer my Pokémon: violet save but .pk9 does not seem to open i tried .bin also does not work hope it get fixed to excited to try this project 

Unfortunately Nintendo Switch save files are not supported yet. `.pk9` files are supported, those are the Pokémon themselves that have been extracted with a program like PKHeX. New save support will happen gradually, but it will happen!
