### ISSUE TITLE
Dropdown Menu Incorrectly rendering PK# files on Windows

### ISSUE THREAD

**Issue by evanwporter** [andrewbenington/OpenHome#70]
It works in the dev version, but when built manually or installed via the provided installers we get the following text:

![image](https://github.com/user-attachments/assets/f400385e-bdc2-4ace-90a3-b7343aad805d)

Clicking on the text doesn't work. 

Will poke around to see if I can identify the issue.

**Comment by evanwporter** [comment]
https://github.com/andrewbenington/OpenHome/blob/788d323179fe714169ed04d617257e4e0fcc3d0a/src/pokemon/FileTypeSelect.tsx#L66-L81

The only ones showing up are the one listed here ^^^

**Comment by andrewbenington** [comment]
the javascript engine used for the windows version must have different behavior for this line:
[> saveType.pkmType.name.replace('_', '')](https://github.com/andrewbenington/OpenHome/blob/788d323179fe714169ed04d617257e4e0fcc3d0a/src/pokemon/FileTypeSelect.tsx#L61)

My lunch is ending soon but I'll poke around with this on Windows after work. I should have waited for you to test before I published 1.0.0, my bad

**Comment by evanwporter** [comment]
@andrewbenington 

On windows at least...some kind of minimization obfuscation method is applied to the class name.

See here:

https://stackoverflow.com/a/36643177

Idk what the solution is here. I think the best way is to call `pkmType.format` but obviously that doesn't work here. Other methods are defining a pkmFormat in each sav...

**Comment by andrewbenington** [comment]
oh youre absolutely right, it's thanks to minification. i'll figure something out

**Comment by andrewbenington** [comment]
Fixed in the latest commit. Going to do a 1.0.1 release

**Comment by andrewbenington** [comment]
@evanwporter actually just to be safe, can you confirm that the fix worked for you? I'm having config issues building on my ARM windows vm

**Comment by evanwporter** [comment]
@andrewbenington 

Works. Good to release.

**Comment by evanwporter** [comment]
27bf39e <= This commit isn't working correctly. Settings aren't allowing getEnabledSaveTypes to correctly return the correct settings.

@andrewbenington

**Comment by andrewbenington** [comment]
@evanwporter could you clarify? is this a typing issue? That commit has typing issues that were fixed in the following commit

**Comment by andrewbenington** [comment]
The dropdown and the settings page work fine for me on Windows in v1.0.1. Try using the latest commit and see if you still have issues

**Comment by evanwporter** [comment]
@andrewbenington 

![image](https://github.com/user-attachments/assets/d571b626-dc33-4907-9a50-60aaf4aa8dcf)

This is with the RR setting enabled. Perhaps my settings.json has not been correctly defined?

**Comment by evanwporter** [comment]
@andrewbenington 

Side note: I was wondering whether the size of the OH sprites could be cut down by converting them to `svg`

**Comment by andrewbenington** [comment]
<img width="714" alt="Screenshot 2024-12-14 at 3 26 12 PM" src="https://github.com/user-attachments/assets/5d278ebf-f8bc-4abb-a947-a2cf2bed427a" />

This is what I see on v1.0.1, downloaded directly from the releases page. Turning on/off RR in the settings page only hides PK3RR from the dropdown, as it should.

Can you, in detail, tell me:
1. The commit you are on in that screenshot
2. The context of that pokemon (is it in a game box/home box? Is that the only pokemon that doesn't show earlier generation options)
3. Does this happen when you use the latest release (v1.0.1)

And no, you can't just convert a bitmap image to a vector image like SVG: https://en.wikipedia.org/wiki/Vector_graphics

**Comment by andrewbenington** [comment]
@evanwporter also can you do an `npm install` to make sure you have the new version of `pokemon-files`

**Comment by evanwporter** [comment]
Latest commit. I'm built the dev and build versions. Will install it.

**Comment by evanwporter** [comment]
@andrewbenington 

Curious the install version works, so idk...

**Comment by andrewbenington** [comment]
@evanwporter Ok I'm getting the same issue in dev mode on Windows. I'll debug and start a discussion on this instead of staying in this issue
