### ISSUE TITLE
bug: release box doesn't work

### ISSUE THREAD

**Issue by evanwporter** [andrewbenington/OpenHome#75]
Probably due to the new drag and drop lib

**Comment by evanwporter** [comment]
@andrewbenington 

I think we should switch the `release` tag to `prerelease` since there seems to be some kinks to work out like #74 and #75

**Comment by andrewbenington** [comment]
Yeah the move to tauri and the new drag+drop library seem to have introduced a bunch of significant issues that haven't all been resolved yet. I think that's a good call.
