### ISSUE TITLE
bug: importing pkm file doesn't work

### ISSUE THREAD

**Issue by andrewbenington** [andrewbenington/OpenHome#79]
Dragging a pkm file into a box should import the mon, as it did before the new drag+drop library

**Comment by evanwporter** [comment]
I noticed you commented that part of the code out...

**Comment by andrewbenington** [comment]
yeah because the way Tauri deals with drag+drop files is different. the code has to be mostly rewritten. so less a 'bug' and more of an 'unmigrated feature'
